# fly.toml app configuration file generated for clipcatalyst-worker on 2025-08-22T23:46:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clipcatalyst-worker'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.concurrency]
    type = 'requests'
    hard_limit = 10
    soft_limit = 8

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
